# Generated by Django 3.2.7 on 2021-11-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='auctions',
            field=models.ManyToManyField(blank=True, related_name='categories', to='auctions.Listing'),
        ),
    ]
