# Generated by Django 3.2.7 on 2021-12-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='actual_price',
            field=models.FloatField(default=0),
        ),
    ]
