# Generated by Django 3.2.7 on 2021-12-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_actual_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='actual_price',
            field=models.FloatField(default=-1),
        ),
    ]
